
export const boatWorks = [
'Check for any signs of leaks',
'Check for cracks or stressed areas',
'Check thru-hulls for rust',
'Check stringers',
'Wash with a pH balanced soap',
'Wax or paint hull',
'Apply primer on the hull',
'Apply antifouling',
'Check and refill water tank',
'Check the drain for clogs',
'Check condensation in pan under evaporator',
'Check flare(s)',
'Check fire extinguisher',
'Check lifejackets - tears or missing parts',
'Check and restock first aid kit',
'Check flashlight and batteries',
'Check and refill spare gas can',
'Check tender for damage',
'Check tender paddles and outboard',
'Check propeller shaft anode',
'Replace propeller shaft anode',
'Check transmission - prop shaft coupling',
'Check gear shaft linkage (outboard)',
'Check the propeller shaft',
'Check the strut',
'Check the cutlass bearing',
'Check the propeller anode',
'Clean the propeller, strut & shaft',
'Check the propeller',
'Check the propeller nuts & cotter pin',
'Grease the prop-shaft before installation',
'Clean raw water intake thru-hull',
'Check seacock(s) open/close smoothly',
'Place emergency plugs by all seacocks',
'Clean raw water strainer',
'Check raw water pump',
'Check the impeller',
'Replace the impeller',
'Check batteries with a multimeter',
'Clean battery tops & terminals',
'Check electrolyte levels - wet-cell batteries',
'Add water to the unsealed wet-cell batteries',
'Check specific gravity of wet-cell batteries',
'Load test a 12-volt battery',
'Check if the alternator works',
'Check starter solenoid',
'Check all cables and connections',
'Check the bilge pump',
'Check water tightness',
'Hatches - check tightness',
'Helm instruments check',
'Service air conditioner',
'Cabin light - check/replace',
'Navigation lights - check/replace',
'Check the mast(s)',
'Check the boom',
'Check the running rigging',
'Centerboard',
'Check all sails',
'Test Marine Radio (voice call)',
'Test Steering (free movement)',
'Test Tilt / Trim',
'Test Bilge Pump',
'Check Galley / Heating Systems', 
'Check Gauges (i.e. batteries)', 
'Check Fuel Amount',
'Ensure Anchor is ready for use',
'Check load of vessel',
'Secure gear from shifting', 
'Check lifejackets',
'Check the Weather Forecast', 
]