
export const engineItems = [
    'Engine oil',
    'Transmission oil',
    'Coolant',
    'Alternator belt',
    'Replace the alternator belt',
    'Water pump belt',
    'Check pulleys',
    'Belts & pulleys alignment',
    'Tighten belts',
    'First fuel filter',
    'Engine fuel filter',
    'Water separator filter', 
    'Check all fuel lines',
    'Replace the fuel lines',
    'Bleed the fuel system (if needed)', 
    'Check spark plugs',
    'Replace spark plugs',
    'Change Oil filter',
    'Check Air filter',
    'Change air filter',
    'Grease control cable ends', 
    'Replace control cables',
    'Check steering cable',
    'Replace steering cable',
    'Liquid in the hydraulic steering system',
    'Grease engine mount threads',
    'Check transom mount (outboard)',
    'Grease all designated points(outboard)',
    'Check fuel pump',
    'Replace fuel pump',
    'Clean carburator',
    'Rebuild carburator',
    'Check fuel tank for contamination',
    'Check the glow plugs',
    'Replace the glow plugs',
    'Check heat exchanger anode',
    'Replace heat exchange anode',
    'Check the exhaust manifold',
    'Check the water lock',
    'Empty the water lock',
    'Check propeller shaft anode',
    'Grease the shaft packing gland',
    'Measure temperature all around the engine',
    'Replace propeller shaft anode',
    'Check transmission - prop shaft coupling',
    'Check gear shaft linkage (outboard)',
    'Check the propeller shaft',
    'Check the strut',
    'Check the cutlass bearing',
    'Check the propeller anode',
    'Clean the propeller, strut & shaft',
    'Check the propeller',
    'Check the propeller nuts & cotter pin',
    'Grease the prop-shaft before installation',
    'Clean raw water intake thru-hull',
    'Check seacock(s) open/close smoothly',
    'Place emergency plugs by all seacocks',
    'Clean raw water strainer',
    'Check raw water pump',
    'Check the impeller',
    'Replace the impeller',
    'Check batteries with a multimeter',
    'Clean battery tops & terminals',
    'Check electrolyte levels - wet-cell batteries',
    'Add water to the unsealed wet-cell batteries',
    'Check specific gravity of wet-cell batteries',
    'Load test a 12-volt battery',
    'Check if the alternator works',
    'Check starter solenoid',
    'Check all cables and connections',
    'Check the bilge pump'
]


